app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views
from blog import views
from main import views

urlpatterns = [
	#path('', views.index, name='index'),
	#path('', views.index, name='site_index'),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls')),
    path('packers/', include('packers.urls')),
    path('accounts/', include('allauth.urls')),
    path('ecommerce/', include('ecommerce.urls')),
   # path('accounts/', include('django.contrib.auth.urls')), # ne
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
#from django.conf.urls import path
from django.urls import path
from blog import views
app_name = 'blog'

urlpatterns = [  
    path('blog/', views.blog, name='blog'),
    #path('blog-single/', views.sblog, name='blog-single'),
    path('blog-single/<slug:slug>/', views.sblog, name='blog-single'),
    path('reply/', views.reply, name='reply'),
       
]

ecommerce/urls.py
#from django.conf.urls import path
from django.urls import path
from . import views
app_name = 'ecommerce'

urlpatterns = [  
    path('ecommerce/', views.ecommerce, name='ecommerce'),
    path('ecommerce-single/', views.ecommerce_single, name='ecommerce-single'),
    path('ecommerce-cart/', views.ecommerce_cart, name='ecommerce-cart'),   
]

main/urls.py
#from django.conf.urls import path
from django.urls import path
from main import views
app_name = 'main'

urlpatterns = [
	path('', views.index, name='index'),
	path('portfolio/', views.port, name='portfolio'),
    path('portfolio-single/', views.port_view, name='portfolio-single'),
    path('FAQS/', views.faq, name='faq'),
    path('404/', views.error, name='404'),
    path('search-result/', views.search_result, name='search-results'),
    path('timeline/', views.timeline, name='timeline'),
    path('team/', views.team, name='team'),
    path('team-single/', views.team_view, name='team-single'),
    path('services/', views.services, name='services'),
    path('services-single/', views.service_view, name='services-single'),
    path('about-us/', views.about, name='about'),
    path('contact-us/', views.contact, name='contact'),
    path('coming-soon/', views.soon, name='coming-soon'),
    path('email-template/', views.email_template, name='email-template'),
]

blog/models.py
from django.db import models

# Create your models here.

#django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver
from ckeditor.fields import RichTextField

def upload_location(instance, filename, **kwargs):
	file_path = 'blog/{author_id}/{title}-{filename}'.format(
			author_id=str(instance.author.id), title=str(instance.title), filename=filename
		)
	return file_path

class BlogPost(models.Model):
	title 						= models.CharField(max_length=50, null=False, blank=False)	
	body						= RichTextField()
	#image 						= models.ImageField(null=True, blank=False)
	#image 						= models.FileField(upload_to='upload_location', blank=True)
	image 						= models.ImageField(upload_to='post_image', null=False, blank=False)		
	date_published 				= models.DateTimeField(auto_now_add=True, verbose_name="data published")
	date_updated 				= models.DateTimeField(auto_now=True, verbose_name="data updated")
	author 						= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	Slug						= models.SlugField(blank=True, unique=True)

	class Meta:
		ordering = ['-date_published']

	def __str__(self):
		return self.title
	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url	
class Comment(models.Model):
    post = models.ForeignKey(BlogPost,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField(max_length=100)
    body = models.TextField()
    reply = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True, verbose_name="data created")
    active = models.BooleanField(default=False)
    Parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    class Meta:
        ordering = ['created_on']

    def __str__(self):
    	#return 'Comment By {}'.format(self.Name)
        return 'Comment by {}'.format(self.name)

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')	

blog/views.py
from django.shortcuts import render
from django.shortcuts import reverse, redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.
from .models import *
from .forms import *

def blog(request):
	posts = BlogPost.objects.all()
	return render(request, 'blog/blog.html',{ 'post': posts})

def reply(request):
    return render(request, 'blog/reply.html',{})

def sblog(request, slug):
    template_name = 'blog/blog-single.html'
    post = get_object_or_404(BlogPost, Slug = slug)
    #post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form})

blog/templates/snippets/header.html
<!---/demosWTR/Freedom/25-04-2020/living-decor-freedom-demo_Free/1040028587/web/index.htmlselect template_id,template_title,template_name,featured_image,featured_image_server_id,
full_image_server_id,full_image from template_down_details where starter_demo_url='/demosWTR/Freedom/25-04-2020/living-decor-freedom-demo_Free/1040028587/web/index.html' lat part:index.html---><!--
Author: W3layouts
Author URL: http://w3layouts.com
-->
<!DOCTYPE html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
	{% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Living Decor interior category Responsive Web Template | Home : W3layouts</title>
  <link rel="stylesheet" href="{% static 'assets/css/style-freedom.css' %}">
</head>
<body>
<!--<script src='../../../../../../../ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script>
<script src="../../../../../../../m.servedby-buysellads.com/monetization.js" type="text/javascript"></script>-->
<!--<script>
(function(){
	if(typeof _bsa !== 'undefined' && _bsa) {
  		// format, zoneKey, segment:value, options
  		_bsa.init('flexbar', 'CKYI627U', 'placement:w3layoutscom');
  	}
})();
</script>
<script>
(function(){
if(typeof _bsa !== 'undefined' && _bsa) {
	// format, zoneKey, segment:value, options
	_bsa.init('fancybar', 'CKYDL2JN', 'placement:demo');
}
})();
</script>
<script>
(function(){
	if(typeof _bsa !== 'undefined' && _bsa) {
  		// format, zoneKey, segment:value, options
  		_bsa.init('stickybox', 'CKYI653J', 'placement:w3layoutscom');
  	}
})();
</script>-->
<!--<script>(function(v,d,o,ai){ai=d.createElement("script");ai.defer=true;ai.async=true;ai.src=v.location.protocol+o;d.head.appendChild(ai);})(window, document, "//a.vdo.ai/core/w3layouts_V2/vdo.ai.js?vdo=34");</script>-->
<!--<div id="codefund">--><!-- fallback content-- </div>-->
<!--<script src="../../../../../../../codefund.io/properties/441/funder.js" async="async"></script>-->

<!-- Global site tag (gtag.js) - Google Analytics -->
<!--<script async src='https://www.googletagmanager.com/gtag/js?id=UA-149859901-1'></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-149859901-1');
</script>-->

<!--<script>
     window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
     ga('create', 'UA-149859901-1', 'demo.w3layouts.com');
     ga('require', 'eventTracker');
     ga('require', 'outboundLinkTracker');
     ga('require', 'urlChangeTracker');
     ga('send', 'pageview');
   </script>-->
<!--<script async src='../../../../../../js/autotrack.js'></script>-->

<meta name="robots" content="index">
<body>
<!--<link rel="stylesheet" href="../../../../../../images/demobar_w3_4thDec2019.css">-->
	<!-- Demo bar start -->
 <!-- <div id="w3lDemoBar" class="w3l-demo-bar">
  <a href="https://w3layouts.com/?p=40440" ga-on="click" ga-event-category="Living Decor Template" ga-event-action="view" ga-event-label="Living Decor - view">
    <span class="w3l-icon -back">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path opacity=".87" fill="none" d="M0 0h24v24H0V0z"/><path d="M16.62 2.99c-.49-.49-1.28-.49-1.77 0L6.54 11.3c-.39.39-.39 1.02 0 1.41l8.31 8.31c.49.49 1.28.49 1.77 0s.49-1.28 0-1.77L9.38 12l7.25-7.25c.48-.48.48-1.28-.01-1.76z"/></svg>
    </span>
    <span class="w3l-text">Back</span>
  </a>
  <a href="https://w3layouts.com/" class="w3l-logo">W3layouts</a>
  <div class="w3l-template-options">
    <a href="https://w3layouts.com/?p=40440"
      class="w3l-download" ga-on="click" ga-event-category="Living Decor Template" ga-event-action="download-options" ga-event-label="Living Decor - Download options" title="Free download requires Backlink">
      <span class="w3l-icon -download">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M19 12v7H5v-7H3v7c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2v-7h-2zm-6 .67l2.59-2.58L17 11.5l-5 5-5-5 1.41-1.41L11 12.67V3h2z"/><path fill="none" d="M0 0h24v24H0z"/></svg>
      </span>
      <span class="w3l-text">Download</span>
    </a>
    <a href="https://w3layouts.com/?p=40440"
      class="w3l-buy" ga-on="click" ga-event-category="Living Decor Template" ga-event-action="Buy Now" ga-event-label="Living Decor - Buy" title="Remove Backlink from template">
      <span class="w3l-icon -buy">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M7 18c-1.1 0-1.99.9-1.99 2S5.9 22 7 22s2-.9 2-2-.9-2-2-2zM1 2v2h2l3.6 7.59-1.35 2.45c-.16.28-.25.61-.25.96 0 1.1.9 2 2 2h12v-2H7.42c-.14 0-.25-.11-.25-.25l.03-.12.9-1.63h7.45c.75 0 1.41-.41 1.75-1.03l3.58-6.49c.08-.14.12-.31.12-.48 0-.55-.45-1-1-1H5.21l-.94-2H1zm16 16c-1.1 0-1.99.9-1.99 2s.89 2 1.99 2 2-.9 2-2-.9-2-2-2z"/><path d="M0 0h24v24H0z" fill="none"/></svg>
      </span>
      <span class="w3l-text">Buy Now</span>
    </a>
  </div>
</div>-->


<!-- inner pages header -->
<section class="w3l-hero-headers-11">
	<div class="hero-header-11-content">
		<div class="top-header">
			<div class="wrapper-full">
				<div class="d-grid grid-columns-2">
					<div class="menu-overlay-left">
					<!-- overlay-menuv-menu -->
						<div class="overlay-menuv-hny">
							<input type="checkbox" id="op"></input>
							<div class="side-menu-hny">
								<label for="op" class="menuopen">
									<p>Menu</p>
								</label>
							</div>
							<div class="overlay-menuv overlay-menuv-hugeinc">
								<label for="op" class="menuclose"></label>
								<nav class="menu-side-over-left">
									<ul class="over-cn-vv">
										<li><a href="{% url 'main:index' %}">Home</a></li>
										<li><a href="{% url 'main:about' %}">About Us</a></li>
										<li><a href="{% url 'main:services' %}">Our Services</a></li>
										<li><a href="{% url 'main:services-single' %}">Services single</a></li>
										<li><a href="{% url 'main:team' %}">Team page</a></li>
										<li><a href="{% url 'main:team-single' %}">Team single</a></li>
										<li><a href="{% url 'main:portfolio' %}">Portfolio</a></li>
										<li><a href="{% url 'main:portfolio-single' %}">Portfolio single</a></li>
									</ul>
									<ul class="over-cn-vv">
										<li><a href="{% url 'blog:blog' %}">Blog Page</a></li>
										
										
										
										<li><a href="{% url 'login'%}">Sign In</a></li>
										<li><a href="{% url 'signup'%}">Sign Up</a></li>
										<li><a href="{% url 'main:faq' %}">faq page</a></li>
										<li><a href="{% url 'main:timeline' %}">Timeline</a></li>
										<li><a href="{% url 'main:404' %}">404 page</a></li>
										<li><a href="{% url 'main:coming-soon' %}">Comingsoon</a></li>
									</ul>
									<ul class="over-cn-vv">
										<li><a href="{% url 'main:email-template' %}">Email template</a></li>
										<li><a href="{% url 'main:search-results' %}">Search results</a></li>
										<li><a href="{% url 'ecommerce:ecommerce' %}">Ecommerce</a></li>
										<li><a href="{% url 'ecommerce:ecommerce-single' %}">Ecommerce single</a></li>
										<li><a href="{% url 'ecommerce:ecommerce-cart' %}">Ecommerce cart</a></li>
										<li><a href="{% url 'main:contact' %}">Contact us</a></li>
									</ul>
								</nav>
							</div>
						</div>
						<!-- //overlay-menuv-menu -->
					</div>
		
					<div class="accounts align-right">
						<ul>
							<li><a href="{% url 'login'%}"> Sign In</a></li>
							<li><a href="{% url 'signup'%}"> Sign Up</a></li>

	    	<li><span class="hello-msg">Hello, {{request.user}}</span>
  <span ><a  class="hello-msg" href="{% url 'logout' %}">Logout</a></span></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		
		<div class="main-header">
			<div class="wrapper-full">
				<div class="d-grid grid-columns-auto">
					<div class="Brand-logo">
					<!--<a class="brand-logo" href="index.html">Living <span>Decor</span></a>-->
					<!--if logo is image enable this  -->
					<a class="brand-logo" href="/">
					<img src="{% static 'assets/images/experts.png' %}" class="img-responsive" alt="Your logo" title="Your logo"  />
					</a>
					</div>
					
					<div class="right-grid align-left d-grid">
						<div class="quick-links">
							<ul>
								<li><a href="{% url 'main:about' %}">About Company <span>few words about us</span></a></li>
								<li><a href="{% url 'main:services' %}">What we offer <span>provided services </span></a></li>
							<!--	<li><a href="blog.html">Interior Blog <span>Featured posts</span></a></li>-->
							</ul>
						</div>
						<div class="button align-right">
							<a href="{% url 'main:contact' %}" class="actionbg">Get In Touch</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>