app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views
from blog import views
from main import views

urlpatterns = [
	#path('', views.index, name='index'),
	#path('', views.index, name='site_index'),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls')),
    path('packers/', include('packers.urls')),
    path('accounts/', include('allauth.urls')),
    path('ecommerce/', include('ecommerce.urls')),
   # path('accounts/', include('django.contrib.auth.urls')), # ne
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
#from django.conf.urls import path
from django.urls import path
from blog import views
app_name = 'blog'

urlpatterns = [  
    path('blog/', views.blog, name='blog'),
    #path('blog-single/', views.sblog, name='blog-single'),
    path('blog-single/<slug:slug>/', views.sblog, name='blog-single'),
    path('reply/', views.reply, name='reply'),
       
]

blog/models.py
from django.db import models

# Create your models here.

#django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver
from ckeditor.fields import RichTextField

def upload_location(instance, filename, **kwargs):
	file_path = 'blog/{author_id}/{title}-{filename}'.format(
			author_id=str(instance.author.id), title=str(instance.title), filename=filename
		)
	return file_path

class BlogPost(models.Model):
	title 						= models.CharField(max_length=50, null=False, blank=False)	
	body						= RichTextField()
	#image 						= models.ImageField(null=True, blank=False)
	#image 						= models.FileField(upload_to='upload_location', blank=True)
	image 						= models.ImageField(upload_to='post_image', null=False, blank=False)		
	date_published 				= models.DateTimeField(auto_now_add=True, verbose_name="data published")
	date_updated 				= models.DateTimeField(auto_now=True, verbose_name="data updated")
	author 						= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	Slug						= models.SlugField(blank=True, unique=True)

	class Meta:
		ordering = ['-date_published']

	def __str__(self):
		return self.title
	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url	
class Comment(models.Model):
    post = models.ForeignKey(BlogPost,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField(max_length=100)
    body = models.TextField()
    reply = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True, verbose_name="data created")
    active = models.BooleanField(default=False)
    Parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    class Meta:
        ordering = ['created_on']

    def __str__(self):
    	#return 'Comment By {}'.format(self.Name)
        return 'Comment by {}'.format(self.name)

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')	

blog/views.py
from django.shortcuts import render
from django.shortcuts import reverse, redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.
from .models import *
from .forms import *

def blog(request):
	posts = BlogPost.objects.all()
	return render(request, 'blog/blog.html',{ 'post': posts})

def reply(request):
    return render(request, 'blog/reply.html',{})

def sblog(request, slug):
    template_name = 'blog/blog-single.html'
    post = get_object_or_404(BlogPost, Slug = slug)
    #post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form})

blog/templates/blog/blog-single.html
{% include 'snippets/header.html' %}
{% load static %}
<style>
	.actionbg {
    border: none;
    display: inline-block;
    font-size: 14px;
    color: #F5F9FC;
    background: #00aeff;
    padding: 10px 10px;
    text-align: center;
    border-radius: 10px !important; }
  .actionbg:hover {
    background: #009de6; }
</style>
<!-- title 11 -->
<section class="w3l-title-11-blog">
	<div class="title11">
		<div class="wrapper">
			<div class="title11-content">
				<h2>Blog Single</h2>
			</div>
		</div>
	</div>
</section>
<!-- //title 11 -->

<!-- text11 -->
<section class="w3l-text-11">
	<div class="text11">
		<div class="wrapper">
			<div class="text11-content">
				<a href="#living" class="tag">Living room</a>
				<h6>August 17th</h6>
				<h4 class="heading-no-margin">Large Collection Of Living Room Furniture</h4>
				
				<h1>{{post.title}}</h1>
				<img src="{{post.imageURL}}" alt="blogposts" width="80%" height="auto" /></a>
				
				<p>{{post.body | safe }} </p>
				<h5>Posted on-{{post.date_published}}-by-{{post.author}} </h5>
				<!--<img src="{% static 'assets/images/services-single.jpg' %}" class="img-responsive margin-top" alt="" />
				<p>Fusce faucibus ante vitae justo efficitur elementum. Donec ipsum faucibus arcu elementum, luctus justo. ac purus semper. Fusce faucibus ante vitae justo efficitur elementum. Donec ipsum faucibus arcu elementum, luctus justo. ac purus semper. Fusce faucibus ante vitae justo efficitur elementum. Donec ipsum faucibus arcu elementum, luctus justo. ac purus semper.</p>-->
				<p>Fusce faucibus ante vitae justo efficitur elementum. Donec ipsum faucibus arcu elementum, luctus justo. ac purus semper. Fusce faucibus ante vitae justo efficitur elementum. Donec ipsum faucibus arcu elementum, luctus justo. ac purus semper."</p>
				<h5 class="quote">"Fusce faucibus ante vitae justo efficitur elementum. Donec ipsum faucibus arcu elementum.</h5>
				<p>Fusce faucibus ante vitae justo efficitur elementum. Donec ipsum faucibus arcu elementum, luctus justo. ac purus semper. Fusce faucibus ante vitae justo efficitur elementum. Donec ipsum faucibus. Donec ipsum faucibus arcu elementum.</p>
				<ul class="blog-list">
					<li>1. Fusce faucibus ante vitae justo efficitur elementum. Donec ipsum faucibus arcu elementum</li>
					<li>2. Donec ipsum faucibus arcu elementum, luctus justo. ac purus semper. Donec ipsum faucibus arcu elementum, luctus justo. ac purus semper.</li>
				</ul>
				<div class="social-share-blog">
					<h4 class="heading-no-margin">Share this post :</h4>
					<ul class="social">
						<li><a href="#facebook"><span class="fa fa-facebook"></span></a></li>
						<li><a href="#twitter"><span class="fa fa-twitter"></span></a></li>
						<li><a href="#google"><span class="fa fa-google-plus"></span></a></li>
						<li><a href="#linkedin"><span class="fa fa-linkedin"></span></a></li>
					</ul>
				</div>
				<div class="comments">
					<h3 class="aside-title ">{{ comments.count }}  Recent Comments</h3>
					<div class="comments-grids">
						<div class="media-grid">
							
							<div class="media">
								<!--<a class="" href="#"><img src="{% static 'assets/images/customer1.jpg' %}" class="img-responsive" width="60px" alt="placeholder image"></a>-->
								{% for comment in comments %}
								<div class="media-body comments-grid-right">
									<h5> {{ comment.name }},</br></h5>
									<ul class="">
										<li class="font-weight-bold">{{ comment.created_on }}
											<i>|</i>
										</li>
										<li>
											<a href="#admin" class="font-weight-bold">Reply by Admin: </a><b> {{comment.reply}}</b>
										</li>
									</ul>
									
								</div>
								<div class="clear"></div>
								<p>{{ comment.body | linebreaks }}</p>
										
								{% endfor %}
							</div>							
						</div>
						
						<!--<div class="media-grid">
							<div class="media">
							<a class="" href="#"><img src="{% static 'assets/images/customer2.jpg' %}" class="img-responsive" width="60px" alt="placeholder image"></a>
							<div class="media-body comments-grid-right">
								<h5>Charlie</h5>
								<ul class="">
									<li class="font-weight-bold">4 mins ago
										<i>|</i>
									</li>
									<li>
										<a href="#comment" class="font-weight-bold">Reply</a>
									</li>
								</ul>
							</div>
							<div class="clear"></div>
							</div>
							<p>Mattis ut hendrerit non, facilisis eget mauris. Sed ultricies nec purus quis	tempor. Phasellus ipsum bibendum eu nec purus quis tempor. Donec ipsum faucibus arcu elementum, luctus justo. purus semper elementum purus quis tempor facilisis eget mauris.</p>
						</div>-->
					</div>
				</div>
				{% if new_comment %}
        		<div class="alert alert-success" role="alert">
         		 Your comment is awaiting moderation
        		</div>
        		{% else %}
				<div class="leave-comment-form" id="comment">
					<h3 class="aside-title">Leave a comment</h3>
					<form  method="post">
						{{comment_form.as_p}}
						{% csrf_token %}

						<div class="submit text-right">
						<button type="submit" class="actionbg">Add Comment</button>
						
						</div>
						<!--<div class="input-grids">
							<div class="form-group">
								<input type="text" name="Name" class="form-control" placeholder="Name" required="">
							</div>
							<div class="form-group">
								<input type="email" name="Email" class="form-control" placeholder="Email" required="">
							</div>
						</div>
						<div class="form-group">
							<textarea name="Message" class="form-control" placeholder="Your reply..." required=""></textarea>
						</div>
						<div class="submit text-right">
							
							<a href="#" class="actionbg">Add Comment</a>
						</div>-->
					</form>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</section>


{% include 'main/snippets/footer.html' %}
{% include 'main/snippets/move_top.html' %}

blog/templates/blog/blog.html
{% include 'snippets/header.html' %}
{% load static %}
<!-- title 11 -->
<section class="w3l-title-11-blog">
	<div class="title11">
		<div class="wrapper">
			<div class="title11-content">
				<h2>
					Interior Designs Blog
					</h2>
			</div>
		</div>
	</div>
</section>
<!-- //title 11 -->

 <div class="w3l-grids-block-5">
 <!-- grids block 5 -->
 <section id="grids5-block">
	<div class="wrapper">
			<div class="d-grid">
				{% for data in post %}
				<div class="grids5-info">
					
         			<a href="{% url 'blog:blog-single' slug=data.Slug %}"><img src="{{data.imageURL}}" alt="blogposts" width="auto" height="auto" /></a>
					<h1>{{data.title}}</h1></a>
					<h5>Posted on-{{data.date_published}}-by-{{data.author}}--{{data.date_updated}} </h5>
						<ul class="blog-info">
							<!--<li><a href="#admin"><span class="fa fa-user"></span> admin</a></li>
							<li><a href="#comments"><span class="fa fa-comments"></span>3 comments</a></li>
							<li><a href="#shares"><span class="fa fa-share"></span>3 shares</a></li>
						</ul>-->
					<h4><a href="{% url 'blog:blog-single' slug=data.Slug  %}">Multi-functional furniture to maximize space</a></h4>
				</div>
				{% endfor %}
				
				
			</div>
			<div class="pagination">
				<ul>
					<li class="prev"><a href="#page-number"><span class="fa fa-angle-double-left"></span></a></li>
					<li><a href="#page-number" class="active">1</a></li>
					<li><a href="#page-number">2</a></li>
					<li><a href="#page-number">3</a></li>
					<li><a href="#page-number">4</a></li>
					<li><a href="#page-number">5</a></li>
					<li class="next"><a href="#page-number"><span class="fa fa-angle-double-right"></span></a></li>
				</ul>
			</div>
		</div>
	</div>
</section>
<!-- // grids block 5 -->



{% include 'main/snippets/footer.html' %}
{% include 'main/snippets/move_top.html' %}

blog/templates/blog/reply.html
{% include 'snippets/header.html' %}
{% load static %}
<!-- title 11 -->
<section class="w3l-title-11-blog">
	<div class="title11">
		<div class="wrapper">
			<div class="title11-content">
				<h2>
					Sorry, only <b>ADMIN</b> can do reply.....
					</h2>
			</div>
		</div>
	</div>
</section>
<!-- //title 11 -->
  

{% include 'main/snippets/footer.html' %}
{% include 'main/snippets/move_top.html' %}