app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views
from blog import views
from main import views

urlpatterns = [
	#path('', views.index, name='index'),
	#path('', views.index, name='site_index'),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls')),
    path('packers/', include('packers.urls')),
    path('accounts/', include('allauth.urls')),
    path('ecommerce/', include('ecommerce.urls')),
   # path('accounts/', include('django.contrib.auth.urls')), # ne
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
#from django.conf.urls import path
from django.urls import path
from main import views
app_name = 'main'

urlpatterns = [
	path('', views.index, name='index'),
	path('portfolio/', views.port, name='portfolio'),
    path('portfolio-single/', views.port_view, name='portfolio-single'),
    path('FAQS/', views.faq, name='faq'),
    path('404/', views.error, name='404'),
    path('search-result/', views.search_result, name='search-results'),
    path('timeline/', views.timeline, name='timeline'),
    path('team/', views.team, name='team'),
    path('team-single/', views.team_view, name='team-single'),
    path('services/', views.services, name='services'),
    path('services-single/', views.service_view, name='services-single'),
    path('about-us/', views.about, name='about'),
    path('contact-us/', views.contact, name='contact'),
    path('coming-soon/', views.soon, name='coming-soon'),
    path('email-template/', views.email_template, name='email-template'),
]

packers/urls.py
#from django.conf.urls import path
from django.urls import path
from . import views
app_name = 'packers'

urlpatterns = [  
    path('packers-and-movers-bangalore/', views.bangalore, name='bangalore'),

       
]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms

class contactForm(forms.Form): #new form called contactForm
 	Username = forms.CharField(required=True,max_length=50,help_text='limit 50 chars')
 	UserEmail = forms.EmailField(required=True)
 	Message = forms.CharField(required=True,widget=forms.Textarea)
	#UserEmail = forms.EmailField(required=True)
	#Message = forms.CharField(required=True,widget=forms.Textarea)
	#This widget overrides the defualt widdget defult in CharField. See Dj Docs.

main/views.py
from django.shortcuts import render
from main.forms import contactForm
from . import autoreply
from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail
# Create your views here.	
from django.shortcuts import reverse, redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.
from blog.models import *
from blog.forms import *
# Homepage
def index(request):
    posts = BlogPost.objects.all()
    #return render(request, 'blog/blog.html',{ 'post': posts})
    return render(request, 'main/index.html', { 'post': posts})

def port(request):
    return render(request, 'main/portfolio.html')


def soon(request):
    return render(request, 'main/coming-soon.html')    

def email_template(request):
    return render(request, 'main/email-template.html')

def search_result(request):
    return render(request, 'main/search-results.html')

def port_view(request):
    return render(request, 'main/portfolio-single.html')

def team(request):
    return render(request, 'main/team.html')

def team_view(request):
    return render(request, 'main/team-single.html')
    
def about(request):
    return render(request, 'main/about.html')

def services(request):
    return render(request, 'main/services.html')

def service_view(request):
    return render(request, 'main/services-single.html')  

def faq(request):
    return render(request, 'main/faq.html')

def timeline(request):
    return render(request, 'main/timeline.html')

def error(request):
    return render(request, 'main/404.html')              

def contact(request):
    """about page"""
    title = "Contact"
    form = contactForm(request.POST or None) #form handling by view.
    confirmation = None

    if form.is_valid():
        user_name = form.cleaned_data['Username']
        user_message = form.cleaned_data['Message']
        emailsub = user_name + " tried contacting you on TOP5PACKERSANDMOVERS ."
        emailFrom = form.cleaned_data['UserEmail']
        emailmessage = '%s %s user email: %s' %(user_message, user_name, emailFrom)
        emailTo = [settings.EMAIL_HOST_USER]
        send_mail(emailsub, emailmessage, emailFrom, list(emailTo), fail_silently=True)
        #Autoreply.
        autoreply.autoreply(emailFrom)
        title = "Thanks."
        confirmation = "We will get right back to you."
        form = None

    context = {'title':title, 'form':form, 'confirmation':confirmation,}
    template = 'contact.html'
    return render(request, 'main/contact.html',context)      

main/templates/main/snippets/base.html
<!---/demosWTR/Freedom/25-04-2020/living-decor-freedom-demo_Free/1040028587/web/index.htmlselect template_id,template_title,template_name,featured_image,featured_image_server_id,
full_image_server_id,full_image from template_down_details where starter_demo_url='/demosWTR/Freedom/25-04-2020/living-decor-freedom-demo_Free/1040028587/web/index.html' lat part:login.html---><!--
Author: W3layouts
Author URL: http://w3layouts.com
-->
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from demo.w3layouts.com/demosWTR/Freedom/25-04-2020/living-decor-freedom-demo_Free/1040028587/web/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 30 May 2020 11:07:08 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
	{% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Living Decor interior category Responsive Web Template | Login : W3layouts</title>
  <link rel="stylesheet" href="{%static 'assets/css/style-freedom.css' %}">
</head>
<body>
<script src='../../../../../../../ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script><script src="../../../../../../../m.servedby-buysellads.com/monetization.js" type="text/javascript"></script>
<script>
(function(){
	if(typeof _bsa !== 'undefined' && _bsa) {
  		// format, zoneKey, segment:value, options
  		_bsa.init('flexbar', 'CKYI627U', 'placement:w3layoutscom');
  	}
})();
</script>
<script>
(function(){
if(typeof _bsa !== 'undefined' && _bsa) {
	// format, zoneKey, segment:value, options
	_bsa.init('fancybar', 'CKYDL2JN', 'placement:demo');
}
})();
</script>
<script>
(function(){
	if(typeof _bsa !== 'undefined' && _bsa) {
  		// format, zoneKey, segment:value, options
  		_bsa.init('stickybox', 'CKYI653J', 'placement:w3layoutscom');
  	}
})();
</script>
<!--<script>(function(v,d,o,ai){ai=d.createElement("script");ai.defer=true;ai.async=true;ai.src=v.location.protocol+o;d.head.appendChild(ai);})(window, document, "//a.vdo.ai/core/w3layouts_V2/vdo.ai.js?vdo=34");</script>-->
<div id="codefund"><!-- fallback content --></div>
<script src="../../../../../../../codefund.io/properties/441/funder.js" async="async"></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src='https://www.googletagmanager.com/gtag/js?id=UA-149859901-1'></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-149859901-1');
</script>

<script>
     window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
     ga('create', 'UA-149859901-1', 'demo.w3layouts.com');
     ga('require', 'eventTracker');
     ga('require', 'outboundLinkTracker');
     ga('require', 'urlChangeTracker');
     ga('send', 'pageview');
   </script>
<script async src='../../../../../../js/autotrack.js'></script>

<meta name="robots" content="noindex">
<body><link rel="stylesheet" href="../../../../../../images/demobar_w3_4thDec2019.css">
	<!-- Demo bar start -->
  <div id="w3lDemoBar" class="w3l-demo-bar">
  <a href="https://w3layouts.com/?p=40440" ga-on="click" ga-event-category="Living Decor Template" ga-event-action="view" ga-event-label="Living Decor - view">
    <span class="w3l-icon -back">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path opacity=".87" fill="none" d="M0 0h24v24H0V0z"/><path d="M16.62 2.99c-.49-.49-1.28-.49-1.77 0L6.54 11.3c-.39.39-.39 1.02 0 1.41l8.31 8.31c.49.49 1.28.49 1.77 0s.49-1.28 0-1.77L9.38 12l7.25-7.25c.48-.48.48-1.28-.01-1.76z"/></svg>
    </span>
    <span class="w3l-text">Back</span>
  </a>
  <a href="https://w3layouts.com/" class="w3l-logo">W3layouts</a>
  <div class="w3l-template-options">
    <a href="https://w3layouts.com/?p=40440"
      class="w3l-download" ga-on="click" ga-event-category="Living Decor Template" ga-event-action="download-options" ga-event-label="Living Decor - Download options" title="Free download requires Backlink">
      <span class="w3l-icon -download">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M19 12v7H5v-7H3v7c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2v-7h-2zm-6 .67l2.59-2.58L17 11.5l-5 5-5-5 1.41-1.41L11 12.67V3h2z"/><path fill="none" d="M0 0h24v24H0z"/></svg>
      </span>
      <span class="w3l-text">Download</span>
    </a>
    <a href="https://w3layouts.com/?p=40440"
      class="w3l-buy" ga-on="click" ga-event-category="Living Decor Template" ga-event-action="Buy Now" ga-event-label="Living Decor - Buy" title="Remove Backlink from template">
      <span class="w3l-icon -buy">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M7 18c-1.1 0-1.99.9-1.99 2S5.9 22 7 22s2-.9 2-2-.9-2-2-2zM1 2v2h2l3.6 7.59-1.35 2.45c-.16.28-.25.61-.25.96 0 1.1.9 2 2 2h12v-2H7.42c-.14 0-.25-.11-.25-.25l.03-.12.9-1.63h7.45c.75 0 1.41-.41 1.75-1.03l3.58-6.49c.08-.14.12-.31.12-.48 0-.55-.45-1-1-1H5.21l-.94-2H1zm16 16c-1.1 0-1.99.9-1.99 2s.89 2 1.99 2 2-.9 2-2-.9-2-2-2z"/><path d="M0 0h24v24H0z" fill="none"/></svg>
      </span>
      <span class="w3l-text">Buy Now</span>
    </a>
  </div>
</div>

<!-- logo header -->
<section class="w3l-logo-header">
	<div class="wrapper">
		<div class="Brand-logo">
				<a class="brand-logo" href="index.html">Living <span>Decor</span></a>
                <!-- if logo is image enable this   
                    <a class="brand-logo" href="index.html">
                        <img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
                    </a> -->
		</div>
	</div>
</section>
<!-- //logo header -->

main/templates/main/snippets/footer.html
<section class="w3l-footer-16">
	<!-- /w3l-footer-16 -->
	<div class="w3l-footer-16-main">
		<div class="wrapper">
			<div class="grid">
				<div class="column">
					<h3>Accounts</h3>
					<ul class="footer-gd-16">
						<li><a href="{% url 'login'%}">Login / sign in</a></li>
						<li><a href="{% url 'signup'%}">Register</a></li>
					</ul>				
				</div>
				<div class="column">
						<h3>Partner's Services</h3>
						<ul class="footer-gd-16">
						<li><a href="{% url 'main:services' %}">Packers & Movers</a></li>
						<li><a href="{% url 'main:services' %}">CCTV Survillience</a></li>
						<li><a href="{% url 'main:services' %}">Interior design</a></li>
						<li><a href="{% url 'main:services' %}">Building Constructors</a></li>
					</ul>
				</div>
				<div class="column">
					<h3>Quick Links</h3>
					<ul class="footer-gd-16">
						<li><a href="{% url 'main:about' %}">About Us</a></li>
						<li><a href="{% url 'main:services' %}">Our Services</a></li>
						<li><a href="{% url 'main:portfolio' %}">News</a></li>
						<li><a href="{% url 'main:contact' %}">FAQ's</a></li>
						<li><a href="{% url 'main:about' %}l">Terms & Conditions</a></li>
					<!--	<li><a href="services.html">News</a></li>
						<li><a href="services.html">News</a></li>-->
						<li><a href="{% url 'main:portfolio' %}">Write Complaint</a></li>
						<li><a href="{% url 'main:contact' %}">Get in touch</a></li>
					</ul>
				</div>
						<!--<div class="column column3">							 
						<h3>Links</h3>
						<ul class="footer-gd-16">
							<li><a href="#url">24/7 support</a></li>
							<li><a href="#url">privacy policy</a></li>
							<li><a href="#url">Terms of use</a></li>
							<li><a href="#url">License</a></li>
						</ul>
					</div>-->
					<!--<div class="column column4">
						<h3>Newsletter </h3>
						<form action="#" class="subscribe" method="post">
							<input type="email" name="email" placeholder="Enter your email" required="">
							<button><span class="fa fa-envelope-o"></span></button>
						</form>
						<p>Subscribe and get our weekly newsletter</p>
						<p>We'll never share your email address</p>
					</div>-->
					<div class="column column3">							 
						<h3>Cities we serve</h3>
						<ul class="footer-gd-16">
							<li><a href="#url">Ahmedabad</a></li>
							<li><a href="{%url 'packers:bangalore' %}">Bangalore</a></li>
							<li><a href="#url">Chandigarh</a></li>
							<li><a href="#url">Chennai</a></li>
							<li><a href="#url">Ahmedabad</a></li>
							<li><a href="#url">Bangalore</a></li>
							<li><a href="#url">Chandigarh</a></li>
							<li><a href="#url">Chennai</a></li>
							<li><a href="#url">Chandigarh</a></li>
							<li><a href="#url">Chennai</a></li>
							
						</ul>
					</div>
					<div class="column column4">							 
						<ul class="footer-gd-16"><br><br>
							<li><a href="#url">24/7 support</a></li>
							<li><a href="#url">privacy policy</a></li>
							<li><a href="#url">Terms of use</a></li>
							<li><a href="#url">License</a></li>
							<li><a href="#url">Ahmedabad</a></li>
							<li><a href="#url">Bangalore</a></li>
							<li><a href="#url">Chandigarh</a></li>
							<li><a href="#url">Chennai</a></li>
							<li><a href="#url">Chandigarh</a></li>
							<li><a href="#url">Chennai</a></li>
						</ul>
					</div>
					<div class="column column5">							 
						<ul class="footer-gd-16"><br></br>
							<li><a href="#url">24/7 support</a></li>
							<li><a href="#url">privacy policy</a></li>
							<li><a href="#url">Terms of use</a></li>
							<li><a href="#url">License</a></li>
							<li><a href="#url">Ahmedabad</a></li>
							<li><a href="#url">Bangalore</a></li>
							<li><a href="#url">Chandigarh</a></li>
							<li><a href="#url">Chennai</a></li>
							<li><a href="#url">Chandigarh</a></li>
							<li><a href="#url">Chennai</a></li>
						</ul>
					</div>
					
			</div>
		</div>
	</div>
</section>
<!-- //w3l-footer-16 -->
<!--======================================End of cities==========================-->

<!-- Footer -->
<section class="w3l-footers-1">
  <div class="footer">
    <div class="wrapper">
      <div class="footer-content">
        <div class="d-grid grid-columns-2">
          <div class="footer-left">
            <p>© 2019 Living Decor. All rights reserved | Designed by <a href="https://w3layouts.com/">W3layouts</a></p>
          </div>
          <div class="footer-right align-right">
            <ul class="social">
              <li><a href="#twitter"><span class="fa fa-facebook"></span></a></li>
              <li><a href="#facebook"><span class="fa fa-twitter"></span></a></li>
              <li><a href="#facebook"><span class="fa fa-google-plus"></span></a></li>
              <li><a href="#facebook"><span class="fa fa-linkedin"></span></a></li>
			  <li><a href="#facebook"><span class="fa fa-instagram"></span></a></li>
			  <li><a href="#facebook"><span class="fa fa-vimeo"></span></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- //Footer -->

main/templates/main/snippets/move_top.html
<!-- move top -->
<button onclick="topFunction()" id="movetop" title="Go to top">
  <span class="fa fa-arrow-up"></span>
</button>
<script>
  // When the user scrolls down 20px from the top of the document, show the button
  window.onscroll = function () {
    scrollFunction()
  };

  function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
      document.getElementById("movetop").style.display = "block";
    } else {
      document.getElementById("movetop").style.display = "none";
    }
  }

  // When the user clicks on the button, scroll to the top of the document
  function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
  }
</script>
<!-- /move top -->